### PR TITLE
Addresses

### PR DESCRIPTION
**Pull request by jascination**
Don't know if this is missing or just not desired, but in Google Maps' KML files there is an "Address" field that this extension overlooks. I've added it to the json output.

### CODE REVIEW

**Comment by tmcw** [comment]
Can you add a testcase for this support - a KML file that contains addresses and produces data with addresses?

**Comment by jascination** [comment]
@tmcw Pretty new to pull requests, do you just want me to add a KML into the test/data directory?

**Comment by tmcw** [comment]
Yep, exactly that! Having a test that includes address data ensures that we don't break your added functionality in the future. Thanks - merging!

**Comment by jascination** [comment]
Woo! This is my first proper featured added to a repo, even though it's minor it feels good :)

**Pull request merged**
